include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_empty_else
    - avoid_multiple_declarations_per_line
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - file_names
    - parameter_assignments
    - prefer_const_constructors
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_nullable_for_final_variable_declarations
    - use_named_constants
    - use_string_buffers